# ===========================================================================
# Project:   Designer
# Copyright: ©2011 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => [:sproutcore, "sproutcore/core_foundation", "bulk_data_source"]