# development:
#   adapter: postgresql
#   encoding: unicode
#   database: joygen_development
#   pool: 5
#   username: pgsql
#   password:
#
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: joygen_test
#   pool: 5
#   username: pgsql
#   password:
#
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: joygen_production
#   pool: 5
#   username: pgsql
#   password:

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: joygen_development
  pool: 5
  username: root
  password: xcvxcv
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: joygen_test
  pool: 5
  username: root
  password: xcvxcv
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: joygen_production
  pool: 5
  username: root
  password: xcvxcv
  host: localhost
  reconnect: true

