development: &development
  adapter: mysql2
  host: localhost
  username: root
  password: xcvxcv
  database: interactiff_development

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password: xcvxcv
  database: interactiff_test

production: &production
  adapter: mysql2
  host: localhost
  database: interactiff_production
  username: interactiff
  password: bs7qtT71
