development:
  sessions:
    default:
      database: joygen_development
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: joygen_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      database: joygen_production
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
