FACEBOOK_API_ID: "541256592583503"
FACEBOOK_SECRET: "dc564c7cba6603c936a684128e790488"
GOOGLE_API_ID: "876382699970.apps.googleusercontent.com"
GOOGLE_SECRET: "sl8iOjyPnBc6jtvv3KXB4OF_"
VKONTAKTE_API_ID: "3689588"
VKONTAKTE_SECRET: "wnjq18Z3rqLweZOklMjw"
GMAIL_USERNAME: "robot@interactiff.net"
GMAIL_PASSWORD: "Bv44g3y1"
GMAIL_DOMAIN: "interactiff.net"